version: '3.1'

services:
    mongo:
        image: mongo
        restart: always
    smtl:
        build: .
        volumes:
                - './public:/usr/src/app/public'
        ports:
                - '3000:3000'
